import turtle
turtle.shape("turtle")
turtle.speed(10)
turtle.forward(100)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(50)
turtle.exitonclick()
