#this program says hello and asks for my name
print('Hello world!')
print('whats your name?')
myName=input()
print('It is good to meet you.' +myName)
print('The length of your name is: ')
print(len(myName))
print('how old are ?')
myAge=input()
print('you will be '+ str(int(myAge)+1)+ 'in a year.')
